
<html>
  <head>
    
<meta charset="utf-8" >

<title>tearing 的博客</title>
<meta name="description" content="だから、きっと今の私は、誰がなんと言おと世界一、幸せな女の子だ">

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<link rel="shortcut icon" href="http://localhost:4000/favicon.ico?v=1582502841990">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.0/katex.min.css">
<link rel="stylesheet" href="http://localhost:4000/styles/main.css">



<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js"></script>



  </head>
  <body>
    <div id="app" class="main">
      <div class="site-header-container">
  <div class="site-header">
    <div class="left">
      <a href="http://localhost:4000">
        <img class="avatar" src="http://localhost:4000/images/avatar.png?v=1582502841990" alt="" width="32px" height="32px">
      </a>
      <a href="http://localhost:4000">
        <h1 class="site-title">tearing 的博客</h1>
      </a>
    </div>
    <div class="right">
      <transition name="fade">
        <i class="icon" :class="{ 'icon-close-outline': menuVisible, 'icon-menu-outline': !menuVisible }" @click="menuVisible = !menuVisible"></i>
      </transition>
    </div>
  </div>
</div>

<transition name="fade">
  <div class="menu-container" style="display: none;" v-show="menuVisible">
    <div class="menu-list">
      
        
          <a href="/" class="menu purple-link">
            首页
          </a>
        
      
        
          <a href="/archives" class="menu purple-link">
            归档
          </a>
        
      
        
          <a href="/tags" class="menu purple-link">
            标签
          </a>
        
      
        
          <a class="menu purple-link" href="SorryYouDoNotHavePermissionToView" class="menu" target="_blank">
            关于
          </a>
        
      
    </div>
  </div>
</transition>


      <div class="content-container">
        
        
<section class="post-item">
    <div class="content">
      <a href="http://localhost:4000/post/luo-gu-ge-ren-zhu-ye/">
        <h2 class="post-title">洛谷个人主页</h2>
      </a>
      <div class="post-abstract">
        
      </div>
      <div class="post-info">
        <span><i class="icon icon-calendar-outline"></i> 20-02-23</span>
        
          <span>
            <i class="icon icon-pricetags-outline"></i>
            
              <a href="http://localhost:4000/tag/-LoCJA2vy/">
                主页
                
              </a>
            
          </span>
        
      </div>
    </div>
    
  </section>

<section class="post-item">
    <div class="content">
      <a href="http://localhost:4000/post/ti-jie-cf755a-polandball-and-hypothesis/">
        <h2 class="post-title">题解 CF755A 【PolandBall and Hypothesis】</h2>
      </a>
      <div class="post-abstract">
        
      </div>
      <div class="post-info">
        <span><i class="icon icon-calendar-outline"></i> 20-02-23</span>
        
          <span>
            <i class="icon icon-pricetags-outline"></i>
            
              <a href="http://localhost:4000/tag/VC_c-FolU/">
                CF题解
                
              </a>
            
          </span>
        
      </div>
    </div>
    
  </section>

<section class="post-item">
    <div class="content">
      <a href="http://localhost:4000/post/ti-jie-cf171a-mysterious-numbers-1/">
        <h2 class="post-title">题解 CF171A 【Mysterious numbers - 1】</h2>
      </a>
      <div class="post-abstract">
        
      </div>
      <div class="post-info">
        <span><i class="icon icon-calendar-outline"></i> 20-02-23</span>
        
          <span>
            <i class="icon icon-pricetags-outline"></i>
            
              <a href="http://localhost:4000/tag/VC_c-FolU/">
                CF题解
                
              </a>
            
          </span>
        
      </div>
    </div>
    
  </section>

<section class="post-item">
    <div class="content">
      <a href="http://localhost:4000/post/ti-jie-cf1064a-make-a-triangle/">
        <h2 class="post-title">题解 CF1064A 【Make a triangle!】</h2>
      </a>
      <div class="post-abstract">
        
      </div>
      <div class="post-info">
        <span><i class="icon icon-calendar-outline"></i> 20-02-23</span>
        
          <span>
            <i class="icon icon-pricetags-outline"></i>
            
              <a href="http://localhost:4000/tag/VC_c-FolU/">
                CF题解
                
              </a>
            
          </span>
        
      </div>
    </div>
    
  </section>

<section class="post-item">
    <div class="content">
      <a href="http://localhost:4000/post/ti-jie-p5613-mtoi2019hei-wen-zi-duo/">
        <h2 class="post-title">题解 P5613 【[MtOI2019]黑蚊子多】</h2>
      </a>
      <div class="post-abstract">
        
      </div>
      <div class="post-info">
        <span><i class="icon icon-calendar-outline"></i> 20-02-23</span>
        
          <span>
            <i class="icon icon-pricetags-outline"></i>
            
              <a href="http://localhost:4000/tag/inUm-3hNF/">
                洛谷题解
                
              </a>
            
          </span>
        
      </div>
    </div>
    
  </section>

<section class="post-item">
    <div class="content">
      <a href="http://localhost:4000/post/ti-jie-at3853-otoshidama/">
        <h2 class="post-title">题解 AT3853 【Otoshidama】</h2>
      </a>
      <div class="post-abstract">
        
      </div>
      <div class="post-info">
        <span><i class="icon icon-calendar-outline"></i> 20-02-23</span>
        
          <span>
            <i class="icon icon-pricetags-outline"></i>
            
              <a href="http://localhost:4000/tag/fKfLMO8T6/">
                AT题解
                
              </a>
            
          </span>
        
      </div>
    </div>
    
  </section>

<section class="post-item">
    <div class="content">
      <a href="http://localhost:4000/post/ti-jie-p5733-shen-ji-6li-1-zi-dong-xiu-zheng/">
        <h2 class="post-title">题解 P5733 【【深基6.例1】自动修正】</h2>
      </a>
      <div class="post-abstract">
        
      </div>
      <div class="post-info">
        <span><i class="icon icon-calendar-outline"></i> 20-02-23</span>
        
          <span>
            <i class="icon icon-pricetags-outline"></i>
            
              <a href="http://localhost:4000/tag/inUm-3hNF/">
                洛谷题解
                
              </a>
            
          </span>
        
      </div>
    </div>
    
  </section>

<section class="post-item">
    <div class="content">
      <a href="http://localhost:4000/post/ti-jie-cf409a-the-great-game/">
        <h2 class="post-title">题解 CF409A 【The Great Game】</h2>
      </a>
      <div class="post-abstract">
        
      </div>
      <div class="post-info">
        <span><i class="icon icon-calendar-outline"></i> 20-02-23</span>
        
          <span>
            <i class="icon icon-pricetags-outline"></i>
            
              <a href="http://localhost:4000/tag/VC_c-FolU/">
                CF题解
                
              </a>
            
          </span>
        
      </div>
    </div>
    
  </section>

<section class="post-item">
    <div class="content">
      <a href="http://localhost:4000/post/ti-jie-at859-yuan-su-noxi-tong-ming/">
        <h2 class="post-title">题解 AT859 【元素の系統名】</h2>
      </a>
      <div class="post-abstract">
        
      </div>
      <div class="post-info">
        <span><i class="icon icon-calendar-outline"></i> 20-02-23</span>
        
          <span>
            <i class="icon icon-pricetags-outline"></i>
            
              <a href="http://localhost:4000/tag/fKfLMO8T6/">
                AT题解
                
              </a>
            
          </span>
        
      </div>
    </div>
    
  </section>

<section class="post-item">
    <div class="content">
      <a href="http://localhost:4000/post/ti-jie-p5712-shen-ji-3li-4-apples/">
        <h2 class="post-title">题解 P5712 【【深基3.例4】Apples】</h2>
      </a>
      <div class="post-abstract">
        
      </div>
      <div class="post-info">
        <span><i class="icon icon-calendar-outline"></i> 20-02-23</span>
        
          <span>
            <i class="icon icon-pricetags-outline"></i>
            
              <a href="http://localhost:4000/tag/inUm-3hNF/">
                洛谷题解
                
              </a>
            
          </span>
        
      </div>
    </div>
    
  </section>


<div class="pagination-container">
  
  
    <a href="http://localhost:4000/page/2" class="next">下一页 <i class="icon-arrow-ios-forward-outline"></i></a>
  
</div>


      </div>

      <div class="site-footer">
  <div class="slogan">だから、きっと今の私は、誰がなんと言おと世界一、幸せな女の子だ</div>
  <div class="social-container">
    
      
    
      
    
      
    
      
    
      
    
  </div>
  Powered by <a href="https://github.com/getgridea/gridea" target="_blank">Gridea</a> | <a class="rss" href="http://localhost:4000/atom.xml" target="_blank">RSS</a>
</div>


    </div>
    <script type="application/javascript">

hljs.initHighlightingOnLoad()

var app = new Vue({
  el: '#app',
  data: {
    menuVisible: false,
  },
})

</script>




  </body>
</html>
